### ISSUE TITLE
Thanks for this project

### ISSUE THREAD

**Issue by XVincentX** [liguori/RawORM#1]
I just wanted to tell you my life completely changed since I'm using this project.

It has no performance impact and it works pretty well. It's so flexible you can do whatever you want and it does not complain. It does not raise exceptions, it does not occupy any memory on your system.

**Comment by XVincentX** [comment]
Is a ball stink manager planned?

**Comment by liguori** [comment]
Of course!! It's planned in Q4 2019

**Comment by XVincentX** [comment]
Resolved with #2
